import fs from 'node:fs';
import path from 'node:path';
import {
  absoluteFromRepo,
  fileExists,
  markdownCell,
  readJson,
  writeJson,
  writeText,
} from './common.mjs';

const project = readJson('work/registry/project.json');
const cases = readJson('work/registry/test-cases.json').cases;
const reviews = readJson('work/registry/human-reviews.json').reviews;
const runs = readJson('work/registry/runs.json').runs;
const bugs = readJson('work/registry/bugs.json').bugs;
const ciRuns = readJson('work/registry/ci-runs.json').runs;
const evidence = readJson('work/registry/evidence.json').items;
const features = readJson('work/registry/postman-features.json').features;
const submission = readJson('work/registry/submission.json');

const reviewByCase = new Map(reviews.map((review) => [review.caseId, review]));
const resultsByCase = new Map();
const latestResultByCase = new Map();
const chronologicalRuns = [...runs].sort((left, right) =>
  Date.parse(left.completedAtUtc ?? left.startedAtUtc) - Date.parse(right.completedAtUtc ?? right.startedAtUtc));
for (const run of chronologicalRuns) {
  for (const result of run.caseResults ?? []) {
    if (!resultsByCase.has(result.caseId)) resultsByCase.set(result.caseId, []);
    resultsByCase.get(result.caseId).push(`${run.id}:${result.result}`);
    latestResultByCase.set(result.caseId, { ...result, runId: run.id });
  }
}
const bugsByCase = new Map();
for (const bug of bugs) {
  for (const caseId of bug.caseIds ?? []) {
    if (!bugsByCase.has(caseId)) bugsByCase.set(caseId, []);
    bugsByCase.get(caseId).push(bug.id);
  }
}

const apiRows = project.selectedApis.map((api) => {
  const apiCases = cases.filter((testCase) => testCase.apiId === api.id);
  const executableCases = apiCases.filter((testCase) =>
    testCase.origin === 'HUMAN' || reviewByCase.get(testCase.id)?.verdict !== 'INVALID');
  const executedCases = executableCases.filter((testCase) => latestResultByCase.has(testCase.id));
  const passedCases = executedCases.filter((testCase) => latestResultByCase.get(testCase.id).result === 'PASS');
  const failedCases = executedCases.filter((testCase) => latestResultByCase.get(testCase.id).result === 'FAIL');
  const knownBugFailures = failedCases.filter((testCase) => (bugsByCase.get(testCase.id) ?? []).length > 0);
  const row = {
    id: api.id,
    pool: api.pool,
    feature: api.featureId,
    endpoint: `${api.method} ${api.path}`,
    aiGenerated: apiCases.filter((testCase) => testCase.origin === 'AI').length,
    humanAdded: apiCases.filter((testCase) => testCase.origin === 'HUMAN').length,
    audited: apiCases.filter((testCase) => testCase.origin === 'AI' && reviewByCase.has(testCase.id)).length,
    executable: executableCases.length,
    executed: executedCases.length,
    passed: passedCases.length,
    failed: failedCases.length,
    knownBugFailures: knownBugFailures.length,
    otherFailures: failedCases.length - knownBugFailures.length,
  };
  if (row.passed + row.failed !== row.executed) throw new Error(`Derived result arithmetic does not reconcile for ${api.id}`);
  return row;
});

const totals = apiRows.reduce((result, row) => {
  for (const field of ['aiGenerated', 'humanAdded', 'audited', 'executable', 'executed', 'passed', 'failed', 'knownBugFailures', 'otherFailures']) result[field] += row[field];
  return result;
}, { aiGenerated: 0, humanAdded: 0, audited: 0, executable: 0, executed: 0, passed: 0, failed: 0, knownBugFailures: 0, otherFailures: 0 });

writeJson('work/generated/test-summary.json', {
  generatedAtUtc: new Date().toISOString(),
  selectedApiCount: project.selectedApis.length,
  apis: apiRows,
  totals,
  bugCount: bugs.filter((bug) => bug.status !== 'candidate').length,
});

const summaryLines = [
  '# HW06 Test Summary (Derived)',
  '',
  '> Generated from `work/registry/`; do not edit this file manually.',
  '',
  '| API | Pool | Feature | Endpoint | AI generated | Human added | Audited | Executable | Executed | Passed | Failed | Known-bug failures | Other failures |',
  '|---|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|',
  ...apiRows.map((row) => `| ${row.id} | ${row.pool} | ${row.feature} | ${row.endpoint} | ${row.aiGenerated} | ${row.humanAdded} | ${row.audited} | ${row.executable} | ${row.executed} | ${row.passed} | ${row.failed} | ${row.knownBugFailures} | ${row.otherFailures} |`),
  '',
  `Selected APIs: ${project.selectedApis.length}`,
  `AI-generated cases: ${totals.aiGenerated}`,
  `Human-added cases: ${totals.humanAdded}`,
  `Executable cases: ${totals.executable}`,
  `Executed cases: ${totals.executed}`,
  `Passed cases: ${totals.passed}`,
  `Failed cases: ${totals.failed}`,
  `Known-bug-related failures: ${totals.knownBugFailures}`,
  `Other failures: ${totals.otherFailures}`,
  `Human-confirmed/published bugs: ${bugs.filter((bug) => bug.status !== 'candidate').length}`,
  '',
];
writeText('work/generated/test-summary.md', `${summaryLines.join('\n')}\n`);
const fr04Summary = apiRows.find((row) => row.feature === 'FR-04');
if (fr04Summary) {
  const fr04SummaryLines = [
    '# FR-04 Test Summary (Derived)',
    '',
    '> Generated from the latest canonical per-case results in `work/registry/runs.json`.',
    '',
    `- AI-generated cases: ${fr04Summary.aiGenerated}`,
    `- Human-added cases: ${fr04Summary.humanAdded}`,
    `- Executable cases: ${fr04Summary.executable}`,
    `- Executed cases: ${fr04Summary.executed}`,
    `- Passed cases: ${fr04Summary.passed}`,
    `- Failed cases: ${fr04Summary.failed}`,
    `- Known-bug-related failures: ${fr04Summary.knownBugFailures}`,
    `- Other failures: ${fr04Summary.otherFailures}`,
    '',
    `Arithmetic check: ${fr04Summary.passed} + ${fr04Summary.failed} = ${fr04Summary.executed}.`,
    '',
  ];
  writeText('out/fr04/test-summary.md', fr04SummaryLines.join('\n'));
}

const traceabilityLines = [
  '# HW06 Traceability Matrix (Derived)',
  '',
  '> Generated from canonical registries. Empty cells mean missing traceability, not absence of a requirement.',
  '',
  '| Case | API | Origin | Requirement refs | AI source context | Human verdict | Run results | Bugs |',
  '|---|---|---|---|---|---|---|---|',
  ...cases.map((testCase) => {
    const review = reviewByCase.get(testCase.id);
    return `| ${markdownCell(testCase.id)} | ${markdownCell(testCase.apiId)} | ${markdownCell(testCase.origin)} | ${markdownCell((testCase.requirementRefs ?? []).join(', '))} | ${markdownCell(testCase.generationContext ?? '')} | ${markdownCell(review?.verdict ?? (testCase.origin === 'HUMAN' ? 'HUMAN-AUTHORED' : 'MISSING'))} | ${markdownCell((resultsByCase.get(testCase.id) ?? []).join(', '))} | ${markdownCell((bugsByCase.get(testCase.id) ?? []).join(', '))} |`;
  }),
  '',
];
writeText('work/generated/traceability.md', `${traceabilityLines.join('\n')}\n`);

const reportableBugs = bugs.filter((bug) => bug.status !== 'candidate');
const bugLines = [
  '# HW06 Bug Report (Derived)',
  '',
  '> Generated from published, human-confirmed records in `work/registry/bugs.json`.',
  '',
  ...reportableBugs.flatMap((bug) => [
    `## ${Number.isInteger(bug.githubIssueNumber) ? `Issue #${bug.githubIssueNumber}` : 'Not published yet'}: ${bug.title}`,
    '',
    `- Status: ${bug.status}`,
    `- Canonical cases supporting the public finding: ${(bug.publicCaseIds ?? bug.caseIds ?? []).join(', ')}`,
    `- Expected: ${bug.expected}`,
    `- Actual: ${bug.actual}`,
    `- GitHub Issue: ${bug.githubIssueUrl ?? 'not published yet; publication needs separate student approval'}`,
    `- Runtime evidence: ${(bug.publicEvidencePaths ?? bug.evidencePaths ?? []).join(', ')}`,
    `- Screenshot evidence: ${(bug.screenshotPaths ?? []).join(', ')}`,
    '',
  ]),
];
writeText('work/generated/bug-report.md', `${bugLines.join('\n')}\n`);
writeText('out/bug-report.md', bugLines.join('\n'));

const postmanFeatureLines = [
  '# HW06 Postman Features (Derived)',
  '',
  '> Generated from `work/registry/postman-features.json`; only features with real evidence are listed.',
  '',
  '| Feature | Verified usage | Evidence |',
  '|---|---|---|',
  ...features.map((feature) => `| ${markdownCell(feature.name)} | ${markdownCell(feature.usage)} | ${markdownCell((feature.evidencePaths ?? []).join(', '))} |`),
  '',
];
writeText('work/generated/postman-features.md', `${postmanFeatureLines.join('\n')}\n`);
writeText('out/postman-features.md', postmanFeatureLines.join('\n'));

function ciReportSummary(run) {
  const report = readJson(run.newmanReportPath);
  return {
    executionCount: report.run?.executions?.length ?? 0,
    assertionsTotal: report.run?.stats?.assertions?.total ?? 0,
    assertionsFailed: report.run?.stats?.assertions?.failed ?? run.failedAssertions,
  };
}

const allPassCiRun = ciRuns.find((run) => run.purpose === 'all-pass');
const intentionalFailureCiRun = ciRuns.find((run) => run.purpose === 'intentional-single-failure');
const canonicalFullSuiteCiRun = ciRuns.find((run) => run.purpose === 'canonical-full-suite');
const ciLines = [
  '# HW06 CI/CD Report (Derived)',
  '',
  '> Generated from `work/registry/ci-runs.json` and registered evidence. Screenshot attestation is reported independently from run verification.',
  '',
  '## Compliance status',
  '',
  '- CI infrastructure and complete canonical FR-04 integration: implemented.',
  '- Existing all-pass and intentional-single-failure smoke demonstration: complete as CI behavior evidence.',
  '- Strict assignment requirement that one pipeline run show "all API test cases passing": **PARTIAL / documented limitation due to confirmed SUT defects**.',
  '- The smoke all-pass result must not be interpreted as all 44 canonical FR-04 cases passing.',
  '',
];
if (canonicalFullSuiteCiRun) {
  const screenshot = evidence.find((item) => item.id === canonicalFullSuiteCiRun.screenshotEvidenceId);
  ciLines.push(
    '## Complete canonical FR-04 suite integration',
    '',
    '- Workflow: `.github/workflows/hw06-fr04-canonical-full-suite.yml` (`HW06 FR-04 Canonical Full Suite`).',
    '- The job installs locked dependencies, starts and reseeds the EShop backend for each independent execution group, and runs the current canonical collections/environment/data with Newman.',
    '- Newman JSON, HTML, stdout, copied inputs, canonical summary, exit codes, and backend logs are uploaded as `hw06-fr04-canonical-full-suite` before the final step exposes the genuine suite result.',
    `- Commit: ${canonicalFullSuiteCiRun.commitSha}`,
    `- GitHub Actions run: ${canonicalFullSuiteCiRun.url}`,
    `- Result: ${canonicalFullSuiteCiRun.conclusion}`,
    `- Canonical logical cases: ${canonicalFullSuiteCiRun.counts.executed}/${canonicalFullSuiteCiRun.counts.executable} executed; ${canonicalFullSuiteCiRun.counts.passed} passed; ${canonicalFullSuiteCiRun.counts.failed} failed.`,
    `- Failure classification: ${canonicalFullSuiteCiRun.counts.knownBugFailures} known-bug failures; ${canonicalFullSuiteCiRun.counts.otherFailures} other/specification-gap failure.`,
    `- Student-header runtime proof: ${canonicalFullSuiteCiRun.runtimeHeaderCoverage.studentHeaderRequests}/${canonicalFullSuiteCiRun.runtimeHeaderCoverage.requests} requests.`,
    `- Main collection SHA-256: ${canonicalFullSuiteCiRun.identities.mainCollectionSha256}`,
    `- Main data SHA-256: ${canonicalFullSuiteCiRun.identities.mainDataSha256}`,
    `- Canonical summary: ${canonicalFullSuiteCiRun.canonicalSummaryPath}`,
    `- Screenshot: ${canonicalFullSuiteCiRun.screenshotEvidenceId} (${screenshot?.path ?? 'missing'}; human attestation ${screenshot?.humanAttestation === true ? 'complete' : 'pending'})`,
    '',
    'The complete canonical FR-04 suite is retained as the authoritative API test suite and is executed in CI without weakening its test oracles. Because the suite currently exposes confirmed SUT defects, its real full-suite CI execution is expected to fail. Changing the expected results, suppressing the confirmed bug cases, or modifying the SUT solely to obtain a green pipeline would invalidate the testing evidence. Therefore, the separate stable-case runs are retained only to demonstrate an all-pass CI state and an intentional single-failure state, while the canonical full-suite CI run demonstrates that the complete FR-04 suite is genuinely integrated into the pipeline.',
    '',
  );
}
ciLines.push(
  '## CI behavior demonstration',
  '',
  '- Workflow: `.github/workflows/hw06-fr04-ci.yml` (`HW06 FR-04 Newman CI Sample`).',
  '- This workflow uses only the explicitly identified stable canonical case `FR04-AI-001` to demonstrate CI mechanics.',
  '- It injects `X-Student-Id: 23127179`, runs Newman, and uploads JSON/HTML/backend evidence as `hw06-fr04-ci-newman`.',
  '',
);
for (const [heading, run] of [['All-pass sample', allPassCiRun], ['Intentional single-failure sample', intentionalFailureCiRun]]) {
  if (!run) continue;
  const summary = ciReportSummary(run);
  const screenshot = evidence.find((item) => item.id === run.screenshotEvidenceId);
  ciLines.push(
    `## ${heading}`,
    '',
    `- Commit: ${run.commitSha}`,
    `- GitHub Actions run: ${run.url}`,
    `- Result: ${run.conclusion}`,
    `- Newman request executions: ${summary.executionCount}`,
    `- Assertions: ${summary.assertionsTotal} total, ${summary.assertionsFailed} failed`,
    `- Failed logical test cases: ${run.failedTests}`,
    `- Newman JSON: ${run.newmanReportPath}`,
    `- Screenshot: ${run.screenshotEvidenceId} (${screenshot?.path ?? 'missing'}; human attestation ${screenshot?.humanAttestation === true ? 'complete' : 'pending'})`,
    '',
  );
}
ciLines.push(
  '## Demonstration integrity note',
  '',
  'The intentional sample adds one transparent assertion named `FR04-AI-001 [CI-DEMO] intentional single failure`; it is not classified as an SUT bug. These two smoke runs demonstrate green/red CI behavior only and do not replace the complete canonical suite or prove that all 44 FR-04 cases pass.',
  '',
);
writeText('work/generated/ci-cd-report.md', `${ciLines.join('\n')}\n`);
writeText('out/ci-cd-report.md', ciLines.join('\n'));

function copyArtifact(source, target) {
  if (!fileExists(source)) throw new Error(`Cannot promote missing FR-04 artifact: ${source}`);
  const targetAbsolute = absoluteFromRepo(target);
  fs.mkdirSync(path.dirname(targetAbsolute), { recursive: true });
  fs.copyFileSync(absoluteFromRepo(source), targetAbsolute);
}

const officialRunIds = project.postman?.officialFr04RunIds ?? [];
const officialRuns = officialRunIds.map((id) => {
  const run = runs.find((candidate) => candidate.id === id);
  if (!run) throw new Error(`Unknown official FR-04 run: ${id}`);
  return run;
});
if (officialRuns.length > 0) {
  const primaryRun = officialRuns.find((run) => run.id === project.postman.officialFr04PrimaryRunId);
  if (!primaryRun) throw new Error('Official FR-04 primary run is not in officialFr04RunIds');
  const promotionPairs = [
    [project.postman.collectionPath, 'out/fr04/postman/FR04-profile.postman_collection.json'],
    [project.postman.supportingCollectionPaths[0], 'out/fr04/postman/FR04-profile-stateful.postman_collection.json'],
    [project.postman.environmentPath, 'out/fr04/postman/FR04-profile.postman_environment.json'],
    [project.postman.dataFiles[0], 'out/fr04/postman/FR04-cases.postman_data.json'],
    ['work/postman/fr04/FR04-target-closure.postman_data.json', 'out/fr04/postman/FR04-target-closure.postman_data.json'],
    ['work/postman/fr04/FR04-target-ai027.postman_data.json', 'out/fr04/postman/FR04-target-ai027.postman_data.json'],
    ['.github/workflows/hw06-fr04-ci.yml', 'out/fr04/ci/hw06-fr04-ci.yml'],
    ['.github/workflows/hw06-fr04-canonical-full-suite.yml', 'out/fr04/ci/hw06-fr04-canonical-full-suite.yml'],
    [primaryRun.rawJsonPath, 'out/fr04/newman/FR04-canonical-input.json'],
    [primaryRun.htmlReportPath, 'out/fr04/newman/FR04-canonical-input.html'],
    [primaryRun.consoleLogPath, 'out/fr04/newman/FR04-canonical-input.stdout.log'],
    [primaryRun.metadataPath, 'out/fr04/newman/FR04-canonical-input.metadata.json'],
  ];
  for (const item of evidence.filter((candidate) => candidate.id.startsWith('EVID-FR04-') && candidate.humanAttestation === true)) {
    promotionPairs.push([item.path, `out/fr04/evidence/${item.id}.png`]);
  }
  const finalizedCiEvidenceIds = new Set([
    'EVID-CI-FR04-ALL-PASS',
    'EVID-CI-FR04-INTENTIONAL-FAILURE',
    'EVID-CI-FR04-CANONICAL-FULL-SUITE',
  ]);
  for (const item of evidence.filter((candidate) => finalizedCiEvidenceIds.has(candidate.id) && candidate.humanAttestation === true)) {
    promotionPairs.push([item.path, `out/fr04/evidence/${item.id}.png`]);
  }
  const statefulRun = officialRuns.find((run) => run.id.includes('final-stateful'));
  if (statefulRun) promotionPairs.push(
    [statefulRun.rawJsonPath, 'out/fr04/newman/FR04-final-stateful.json'],
    [statefulRun.htmlReportPath, 'out/fr04/newman/FR04-final-stateful.html'],
    [statefulRun.consoleLogPath, 'out/fr04/newman/FR04-final-stateful.stdout.log'],
    [statefulRun.metadataPath, 'out/fr04/newman/FR04-final-stateful.metadata.json'],
  );
  const closureRun = officialRuns.find((run) => run.dataPath?.endsWith('FR04-target-closure.postman_data.json'));
  if (closureRun) promotionPairs.push(
    [closureRun.rawJsonPath, 'out/fr04/newman/FR04-final-closure.json'],
    [closureRun.htmlReportPath, 'out/fr04/newman/FR04-final-closure.html'],
    [closureRun.consoleLogPath, 'out/fr04/newman/FR04-final-closure.stdout.log'],
    [closureRun.metadataPath, 'out/fr04/newman/FR04-final-closure.metadata.json'],
  );
  const ai027Run = officialRuns.find((run) => run.dataPath?.endsWith('FR04-target-ai027.postman_data.json'));
  if (ai027Run) promotionPairs.push(
    [ai027Run.rawJsonPath, 'out/fr04/newman/FR04-ai027-corrected.json'],
    [ai027Run.htmlReportPath, 'out/fr04/newman/FR04-ai027-corrected.html'],
    [ai027Run.consoleLogPath, 'out/fr04/newman/FR04-ai027-corrected.stdout.log'],
    [ai027Run.metadataPath, 'out/fr04/newman/FR04-ai027-corrected.metadata.json'],
  );
  for (const [source, target] of promotionPairs) copyArtifact(source, target);
  const manifestLines = [
    '# FR-04 Finalized Artifacts',
    '',
    '> Promoted from canonical registries and official raw runs by `npm run hw06:derive`.',
    '',
    `- Primary run: ${primaryRun.id}`,
    `- Collection SHA-256: ${primaryRun.collectionSha256}`,
    `- Environment SHA-256: ${primaryRun.environmentSha256}`,
    `- Data SHA-256: ${primaryRun.dataSha256}`,
    `- Primary Newman HTML: out/fr04/newman/FR04-canonical-input.html`,
    `- Supporting official runs: ${officialRuns.filter((run) => run.id !== primaryRun.id).map((run) => run.id).join(', ')}`,
    '- Finalized CI demo screenshots: out/fr04/evidence/EVID-CI-FR04-ALL-PASS.png and out/fr04/evidence/EVID-CI-FR04-INTENTIONAL-FAILURE.png',
    '- CI workflow configurations: out/fr04/ci/hw06-fr04-ci.yml and out/fr04/ci/hw06-fr04-canonical-full-suite.yml',
    evidence.find((item) => item.id === 'EVID-CI-FR04-CANONICAL-FULL-SUITE' && item.humanAttestation === true)
      ? '- Finalized canonical full-suite CI screenshot: out/fr04/evidence/EVID-CI-FR04-CANONICAL-FULL-SUITE.png'
      : '- Canonical full-suite CI screenshot remains under work/evidence until explicit human attestation.',
    '',
    'The primary run preserves genuine bug-revealing failures. Latest canonical per-case results across the listed official runs are summarized in `work/generated/test-summary.md`.',
    '',
  ];
  writeText('out/fr04/README.md', manifestLines.join('\n'));
}

const fr08Config = project.postmanFr08;
const fr08Summary = apiRows.find((row) => row.feature === 'FR-08');
if (fr08Config && fr08Summary && fr08Summary.executed > 0) {
  const fr08Runs = (fr08Config.officialRunIds ?? []).map((id) => {
    const run = runs.find((candidate) => candidate.id === id);
    if (!run) throw new Error(`Unknown official FR-08 run: ${id}`);
    return run;
  });
  const fr08Primary = fr08Runs.find((run) => run.id === fr08Config.officialPrimaryRunId);
  if (!fr08Primary) throw new Error('Official FR-08 primary run is not in officialRunIds');

  const fr08SummaryLines = [
    '# FR-08 Test Summary (Derived)',
    '',
    '> Generated from `work/registry/*.json` by `npm run hw06:derive`. Raw Newman evidence outranks this file.',
    '',
    `- Selected API: ${fr08Summary.endpoint}`,
    `- AI-generated cases: ${fr08Summary.aiGenerated}`,
    `- Human-added cases: ${fr08Summary.humanAdded}`,
    `- Executable cases: ${fr08Summary.executable}`,
    `- Executed cases: ${fr08Summary.executed}`,
    `- Passed cases: ${fr08Summary.passed}`,
    `- Failed cases: ${fr08Summary.failed}`,
    `- Known-bug-related failures: ${fr08Summary.knownBugFailures}`,
    `- Other failures: ${fr08Summary.otherFailures}`,
    '',
    `Arithmetic check: ${fr08Summary.passed} + ${fr08Summary.failed} = ${fr08Summary.executed}.`,
    '',
    'Evidence limitation recorded at execution time: because the implementation does not derive the total from the cart at all, cases whose client-supplied total happened to equal the cart-derived total pass without proving that any server-side derivation occurs. The passed count must not be read as evidence that checkout recalculates the total.',
    '',
  ];
  writeText('out/fr08/test-summary.md', fr08SummaryLines.join('\n'));

  const fr08Pairs = [
    [fr08Config.collectionPath, 'out/fr08/postman/FR08-checkout.postman_collection.json'],
    [fr08Config.environmentPath, 'out/fr08/postman/FR08-checkout.postman_environment.json'],
    [fr08Config.dataFiles[0], 'out/fr08/postman/FR08-checkout.data.json'],
    [fr08Primary.rawJsonPath, 'out/fr08/newman/FR08-canonical-full-suite.json'],
    [fr08Primary.htmlReportPath, 'out/fr08/newman/FR08-canonical-full-suite.html'],
    [fr08Primary.consoleLogPath, 'out/fr08/newman/FR08-canonical-full-suite.stdout.log'],
    [fr08Primary.metadataPath, 'out/fr08/newman/FR08-canonical-full-suite.metadata.json'],
  ];
  for (const item of fr08Config.manualImportPaths ?? []) {
    fr08Pairs.push([item, `out/fr08/postman/manual-import/${path.basename(item)}`]);
  }
  for (const item of fr08Config.ciWorkflowPaths ?? []) {
    fr08Pairs.push([item, `out/fr08/ci/${path.basename(item)}`]);
  }
  const fr08EvidencePrefixes = ['EVID-FR08-', 'EVID-CI-FR08-'];
  const promotedFr08Evidence = evidence.filter((item) =>
    fr08EvidencePrefixes.some((prefix) => item.id.startsWith(prefix)) && item.humanAttestation === true);
  for (const item of promotedFr08Evidence) fr08Pairs.push([item.path, `out/fr08/evidence/${item.id}.png`]);
  for (const [source, target] of fr08Pairs) copyArtifact(source, target);

  const pendingFr08Evidence = evidence.filter((item) =>
    fr08EvidencePrefixes.some((prefix) => item.id.startsWith(prefix)) && item.humanAttestation !== true);
  const fr08Bugs = bugs.filter((bug) => (bug.caseIds ?? []).some((id) => id.startsWith('FR08-')));
  const fr08ManifestLines = [
    '# FR-08 Finalized Artifacts',
    '',
    '> Promoted from canonical registries and the official raw run by `npm run hw06:derive`.',
    '',
    `- Primary run: ${fr08Primary.id}`,
    `- Collection SHA-256: ${fr08Primary.collectionSha256}`,
    `- Environment SHA-256: ${fr08Primary.environmentSha256}`,
    `- Data SHA-256: ${fr08Primary.dataSha256}`,
    `- Newman exit code preserved: ${fr08Primary.exitCode}`,
    `- Runtime student-header coverage: ${fr08Primary.studentHeaderRequests}/${fr08Primary.executionCount} executed requests`,
    '- Primary Newman HTML: out/fr08/newman/FR08-canonical-full-suite.html',
    '- Postman Desktop manual-import copies: out/fr08/postman/manual-import/',
    `- CI workflow configuration: ${(fr08Config.ciWorkflowPaths ?? []).map((item) => `out/fr08/ci/${path.basename(item)}`).join(', ')}`,
    `- Published bugs: ${fr08Bugs.filter((bug) => bug.status === 'published').map((bug) => `${bug.id} (#${bug.githubIssueNumber})`).join(', ') || 'none'}`,
    `- Promoted attested evidence: ${promotedFr08Evidence.map((item) => item.id).join(', ') || 'none'}`,
    pendingFr08Evidence.length
      ? `- Pending student attestation, still under work/evidence: ${pendingFr08Evidence.map((item) => item.id).join(', ')}`
      : '- All FR-08 evidence carries explicit student attestation.',
    '',
    'The primary run preserves genuine bug-revealing failures and its original exit code. Its 19 failures map to the two published bugs; no oracle was changed after results were observed.',
    '',
  ];
  writeText('out/fr08/README.md', fr08ManifestLines.join('\n'));
}

const fr15Config = project.postmanFr15;
const fr15Summary = apiRows.find((row) => row.feature === 'FR-15');
if (fr15Config && fr15Summary && fr15Summary.executed > 0) {
  const fr15Runs = (fr15Config.officialRunIds ?? []).map((id) => {
    const run = runs.find((candidate) => candidate.id === id);
    if (!run) throw new Error(`Unknown official FR-15 run: ${id}`);
    return run;
  });
  const fr15Primary = fr15Runs.find((run) => run.id === fr15Config.officialPrimaryRunId);
  if (!fr15Primary) throw new Error('Official FR-15 primary run is not in officialRunIds');
  const fr15SpecGap = (fr15Primary.caseResults ?? []).filter(
    (result) => result.classification === 'SPEC-GAP-OBSERVATION',
  ).length;
  const fr15AuthoritativePass = fr15Summary.passed - fr15SpecGap;
  if (fr15AuthoritativePass + fr15Summary.failed + fr15SpecGap !== fr15Summary.executed) {
    throw new Error('FR-15 PASS/FAIL/SPEC-GAP accounting does not reconcile');
  }

  const fr15SummaryLines = [
    '# FR-15 Test Summary (Derived)',
    '',
    '> Generated from `work/registry/*.json` by `npm run hw06:derive`. Raw Newman evidence outranks this file.',
    '',
    `- Selected API: ${fr15Summary.endpoint}`,
    `- AI-generated cases: ${fr15Summary.aiGenerated}`,
    `- Human-added cases: ${fr15Summary.humanAdded}`,
    `- Executable and executed cases: ${fr15Summary.executed}`,
    `- Authoritative PASS cases: ${fr15AuthoritativePass}`,
    `- Authoritative FAIL cases: ${fr15Summary.failed}`,
    `- PASS-shaped SPEC-GAP observations: ${fr15SpecGap}`,
    `- Known-bug-related failures: ${fr15Summary.knownBugFailures}`,
    `- Other failures: ${fr15Summary.otherFailures}`,
    '',
    `Three-way arithmetic check: ${fr15AuthoritativePass} + ${fr15Summary.failed} + ${fr15SpecGap} = ${fr15Summary.executed}.`,
    '',
    'SPEC-GAP observations preserve real runtime results but do not claim undocumented status codes, response schemas, UI escaping, or internal SQL implementation details. They are reported separately from authoritative PASS and FAIL cases.',
    '',
  ];
  writeText('out/fr15/test-summary.md', fr15SummaryLines.join('\n'));

  const fr15RunNames = new Map([
    ['RUN-20260823102155874-fr15-canonical-full-suite', 'FR15-canonical-full-suite'],
    ['RUN-20260823102829114-fr15-auth-reproduction', 'FR15-authorization-reproduction'],
    ['RUN-20260823102841701-fr15-validation-reproduction', 'FR15-validation-reproduction'],
  ]);
  const fr15Pairs = [
    [fr15Config.collectionPath, 'out/fr15/postman/FR15-products.postman_collection.json'],
    [fr15Config.environmentPath, 'out/fr15/postman/FR15-products.postman_environment.json'],
    [fr15Config.dataFiles[0], 'out/fr15/postman/FR15-products.postman_data.json'],
    ['work/postman/fr15/FR15-target-authorization.postman_data.json', 'out/fr15/postman/FR15-target-authorization.postman_data.json'],
    ['work/postman/fr15/FR15-target-validation.postman_data.json', 'out/fr15/postman/FR15-target-validation.postman_data.json'],
    ['work/postman/fr15/README.md', 'out/fr15/postman/README.md'],
    ['work/postman/fr15/build.mjs', 'out/fr15/postman/build.mjs'],
  ];
  for (const run of fr15Runs) {
    const name = fr15RunNames.get(run.id);
    if (!name) throw new Error(`No curated FR-15 name for run: ${run.id}`);
    fr15Pairs.push(
      [run.rawJsonPath, `out/fr15/newman/${name}.json`],
      [run.htmlReportPath, `out/fr15/newman/${name}.html`],
      [run.consoleLogPath, `out/fr15/newman/${name}.stdout.log`],
      [run.metadataPath, `out/fr15/newman/${name}.metadata.json`],
    );
  }
  for (const item of fr15Config.ciWorkflowPaths ?? []) {
    fr15Pairs.push([item, `out/fr15/ci/${path.basename(item)}`]);
  }
  const fr15EvidencePrefixes = ['EVID-FR15-', 'EVID-CI-FR15-'];
  const promotedFr15Evidence = evidence.filter((item) =>
    fr15EvidencePrefixes.some((prefix) => item.id.startsWith(prefix)) && item.humanAttestation === true);
  for (const item of promotedFr15Evidence) fr15Pairs.push([item.path, `out/fr15/evidence/${item.id}.png`]);
  for (const [source, target] of fr15Pairs) copyArtifact(source, target);

  const pendingFr15Evidence = evidence.filter((item) =>
    fr15EvidencePrefixes.some((prefix) => item.id.startsWith(prefix)) && item.humanAttestation !== true);
  const fr15Bugs = bugs.filter((bug) => (bug.caseIds ?? []).some((id) => id.startsWith('FR15-')));
  const fr15CiRuns = ciRuns.filter((run) => run.screenshotEvidenceId?.startsWith('EVID-CI-FR15-'));
  const fr15ManifestLines = [
    '# FR-15 Finalized Artifacts',
    '',
    '> Promoted from canonical registries and immutable execution evidence by `npm run hw06:derive`.',
    '',
    `- Primary run: ${fr15Primary.id}`,
    `- Collection SHA-256: ${fr15Primary.collectionSha256}`,
    `- Environment SHA-256: ${fr15Primary.environmentSha256}`,
    `- Data SHA-256: ${fr15Primary.dataSha256}`,
    `- Newman exit code preserved: ${fr15Primary.exitCode}`,
    `- Runtime student-header coverage: ${fr15Primary.studentHeaderRequests}/${fr15Primary.executionCount} executed requests`,
    '- Primary Newman HTML: out/fr15/newman/FR15-canonical-full-suite.html',
    '- Targeted bug reproductions: out/fr15/newman/FR15-authorization-reproduction.html and out/fr15/newman/FR15-validation-reproduction.html',
    `- CI workflow configuration: ${(fr15Config.ciWorkflowPaths ?? []).map((item) => `out/fr15/ci/${path.basename(item)}`).join(', ')}`,
    `- CI evidence: ${fr15CiRuns.map((run) => `${run.purpose} ${run.url}`).join('; ')}`,
    `- Published bugs: ${fr15Bugs.filter((bug) => bug.status === 'published').map((bug) => `${bug.id} (#${bug.githubIssueNumber})`).join(', ') || 'none'}`,
    `- Promoted attested evidence (${promotedFr15Evidence.length}): ${promotedFr15Evidence.map((item) => item.id).join(', ') || 'none'}`,
    pendingFr15Evidence.length
      ? `- Pending student attestation, still under work/evidence: ${pendingFr15Evidence.map((item) => item.id).join(', ')}`
      : '- All FR-15 evidence carries explicit student attestation.',
    '',
    'The canonical run preserves all genuine failures and its original non-zero exit code. The 28 failures map to the two published root bugs; 15 PASS-shaped observations remain explicitly classified as SPEC-GAP instead of being promoted to authoritative PASS.',
    '',
  ];
  writeText('out/fr15/README.md', fr15ManifestLines.join('\n'));
}

for (const bug of bugs.filter((item) => item.status !== 'candidate')) {
  const issueBody = [
    `# ${bug.id}: ${bug.title}`,
    '',
    `Test cases: ${(bug.publicCaseIds ?? bug.caseIds ?? []).join(', ')}`,
    '',
    '## Expected behavior',
    '',
    bug.expected,
    '',
    '## Actual behavior',
    '',
    bug.actual,
    '',
    '## Reproduction',
    '',
    bug.reproduction ?? 'NOT RECORDED',
    '',
    '## Local evidence paths',
    '',
    ...(bug.publicEvidencePaths ?? bug.evidencePaths ?? []).map((item) => `- ${item}`),
    '',
    '> Attach the required screenshot in GitHub before publishing. A local path is not a public attachment.',
    '',
  ];
  writeText(`work/generated/issues/${bug.id}.md`, `${issueBody.join('\n')}\n`);
}

const evidenceTypes = new Set(evidence.map((item) => item.type));
function artifactPath(artifact) {
  if (artifact.path) return artifact.path;
  if (artifact.pathFrom === 'project.postman.collectionPath') return project.postman?.collectionPath;
  return null;
}
const submissionLines = [
  '# HW06 Submission Status (Derived)',
  '',
  '| Requirement | Source | Status |',
  '|---|---|---|',
  ...(submission.requiredArtifacts ?? []).map((artifact) => {
    const candidatePath = artifactPath(artifact);
    const present = candidatePath ? fileExists(candidatePath) : evidenceTypes.has(artifact.evidenceType);
    return `| ${artifact.id} | ${candidatePath ?? `evidence:${artifact.evidenceType}`} | ${present ? 'PRESENT' : 'MISSING'} |`;
  }),
  '',
  '## Required evidence types',
  '',
  ...(submission.requiredEvidenceTypes ?? []).map((type) => `- [${evidenceTypes.has(type) ? 'x' : ' '}] ${type}`),
  '',
  `CI all-pass records: ${ciRuns.filter((run) => run.purpose === 'all-pass').length}`,
  `CI intentional-single-failure records: ${ciRuns.filter((run) => run.purpose === 'intentional-single-failure').length}`,
  `Postman features recorded: ${features.length}`,
  '',
];
writeText('work/generated/submission-status.md', `${submissionLines.join('\n')}\n`);

process.stdout.write('Generated factual summaries under work/generated/.\n');
