import fs from 'node:fs';
import path from 'node:path';
import {
  absoluteFromRepo,
  fileExists,
  markdownCell,
  readJson,
  writeJson,
  writeText,
} from './common.mjs';

const project = readJson('work/registry/project.json');
const cases = readJson('work/registry/test-cases.json').cases;
const reviews = readJson('work/registry/human-reviews.json').reviews;
const runs = readJson('work/registry/runs.json').runs;
const bugs = readJson('work/registry/bugs.json').bugs;
const ciRuns = readJson('work/registry/ci-runs.json').runs;
const evidence = readJson('work/registry/evidence.json').items;
const features = readJson('work/registry/postman-features.json').features;
const submission = readJson('work/registry/submission.json');

const reviewByCase = new Map(reviews.map((review) => [review.caseId, review]));
const resultsByCase = new Map();
const latestResultByCase = new Map();
const chronologicalRuns = [...runs].sort((left, right) =>
  Date.parse(left.completedAtUtc ?? left.startedAtUtc) - Date.parse(right.completedAtUtc ?? right.startedAtUtc));
for (const run of chronologicalRuns) {
  for (const result of run.caseResults ?? []) {
    if (!resultsByCase.has(result.caseId)) resultsByCase.set(result.caseId, []);
    resultsByCase.get(result.caseId).push(`${run.id}:${result.result}`);
    latestResultByCase.set(result.caseId, { ...result, runId: run.id });
  }
}
const bugsByCase = new Map();
for (const bug of bugs) {
  for (const caseId of bug.caseIds ?? []) {
    if (!bugsByCase.has(caseId)) bugsByCase.set(caseId, []);
    bugsByCase.get(caseId).push(bug.id);
  }
}

const apiRows = project.selectedApis.map((api) => {
  const apiCases = cases.filter((testCase) => testCase.apiId === api.id);
  const executableCases = apiCases.filter((testCase) =>
    testCase.origin === 'HUMAN' || reviewByCase.get(testCase.id)?.verdict !== 'INVALID');
  const executedCases = executableCases.filter((testCase) => latestResultByCase.has(testCase.id));
  const passedCases = executedCases.filter((testCase) => latestResultByCase.get(testCase.id).result === 'PASS');
  const failedCases = executedCases.filter((testCase) => latestResultByCase.get(testCase.id).result === 'FAIL');
  const knownBugFailures = failedCases.filter((testCase) => (bugsByCase.get(testCase.id) ?? []).length > 0);
  const row = {
    id: api.id,
    pool: api.pool,
    feature: api.featureId,
    endpoint: `${api.method} ${api.path}`,
    aiGenerated: apiCases.filter((testCase) => testCase.origin === 'AI').length,
    humanAdded: apiCases.filter((testCase) => testCase.origin === 'HUMAN').length,
    audited: apiCases.filter((testCase) => testCase.origin === 'AI' && reviewByCase.has(testCase.id)).length,
    executable: executableCases.length,
    executed: executedCases.length,
    passed: passedCases.length,
    failed: failedCases.length,
    knownBugFailures: knownBugFailures.length,
    otherFailures: failedCases.length - knownBugFailures.length,
  };
  if (row.passed + row.failed !== row.executed) throw new Error(`Derived result arithmetic does not reconcile for ${api.id}`);
  return row;
});

const totals = apiRows.reduce((result, row) => {
  for (const field of ['aiGenerated', 'humanAdded', 'audited', 'executable', 'executed', 'passed', 'failed', 'knownBugFailures', 'otherFailures']) result[field] += row[field];
  return result;
}, { aiGenerated: 0, humanAdded: 0, audited: 0, executable: 0, executed: 0, passed: 0, failed: 0, knownBugFailures: 0, otherFailures: 0 });

writeJson('work/generated/test-summary.json', {
  generatedAtUtc: new Date().toISOString(),
  selectedApiCount: project.selectedApis.length,
  apis: apiRows,
  totals,
  bugCount: bugs.filter((bug) => bug.status !== 'candidate').length,
});

const summaryLines = [
  '# HW06 Test Summary (Derived)',
  '',
  '> Generated from `work/registry/`; do not edit this file manually.',
  '',
  '| API | Pool | Feature | Endpoint | AI generated | Human added | Audited | Executable | Executed | Passed | Failed | Known-bug failures | Other failures |',
  '|---|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|',
  ...apiRows.map((row) => `| ${row.id} | ${row.pool} | ${row.feature} | ${row.endpoint} | ${row.aiGenerated} | ${row.humanAdded} | ${row.audited} | ${row.executable} | ${row.executed} | ${row.passed} | ${row.failed} | ${row.knownBugFailures} | ${row.otherFailures} |`),
  '',
  `Selected APIs: ${project.selectedApis.length}`,
  `AI-generated cases: ${totals.aiGenerated}`,
  `Human-added cases: ${totals.humanAdded}`,
  `Executable cases: ${totals.executable}`,
  `Executed cases: ${totals.executed}`,
  `Passed cases: ${totals.passed}`,
  `Failed cases: ${totals.failed}`,
  `Known-bug-related failures: ${totals.knownBugFailures}`,
  `Other failures: ${totals.otherFailures}`,
  `Human-confirmed/published bugs: ${bugs.filter((bug) => bug.status !== 'candidate').length}`,
  '',
];
writeText('work/generated/test-summary.md', `${summaryLines.join('\n')}\n`);
const fr04Summary = apiRows.find((row) => row.feature === 'FR-04');
if (fr04Summary) {
  const fr04SummaryLines = [
    '# FR-04 Test Summary (Derived)',
    '',
    '> Generated from the latest canonical per-case results in `work/registry/runs.json`.',
    '',
    `- AI-generated cases: ${fr04Summary.aiGenerated}`,
    `- Human-added cases: ${fr04Summary.humanAdded}`,
    `- Executable cases: ${fr04Summary.executable}`,
    `- Executed cases: ${fr04Summary.executed}`,
    `- Passed cases: ${fr04Summary.passed}`,
    `- Failed cases: ${fr04Summary.failed}`,
    `- Known-bug-related failures: ${fr04Summary.knownBugFailures}`,
    `- Other failures: ${fr04Summary.otherFailures}`,
    '',
    `Arithmetic check: ${fr04Summary.passed} + ${fr04Summary.failed} = ${fr04Summary.executed}.`,
    '',
  ];
  writeText('out/fr04/test-summary.md', fr04SummaryLines.join('\n'));
}

const traceabilityLines = [
  '# HW06 Traceability Matrix (Derived)',
  '',
  '> Generated from canonical registries. Empty cells mean missing traceability, not absence of a requirement.',
  '',
  '| Case | API | Origin | Requirement refs | AI source context | Human verdict | Run results | Bugs |',
  '|---|---|---|---|---|---|---|---|',
  ...cases.map((testCase) => {
    const review = reviewByCase.get(testCase.id);
    return `| ${markdownCell(testCase.id)} | ${markdownCell(testCase.apiId)} | ${markdownCell(testCase.origin)} | ${markdownCell((testCase.requirementRefs ?? []).join(', '))} | ${markdownCell(testCase.generationContext ?? '')} | ${markdownCell(review?.verdict ?? (testCase.origin === 'HUMAN' ? 'HUMAN-AUTHORED' : 'MISSING'))} | ${markdownCell((resultsByCase.get(testCase.id) ?? []).join(', '))} | ${markdownCell((bugsByCase.get(testCase.id) ?? []).join(', '))} |`;
  }),
  '',
];
writeText('work/generated/traceability.md', `${traceabilityLines.join('\n')}\n`);

const reportableBugs = bugs.filter((bug) => bug.status !== 'candidate');
const bugLines = [
  '# HW06 Bug Report (Derived)',
  '',
  '> Generated from published, human-confirmed records in `work/registry/bugs.json`.',
  '',
  ...reportableBugs.flatMap((bug) => [
    `## Issue #${bug.githubIssueNumber}: ${bug.title}`,
    '',
    `- Status: ${bug.status}`,
    `- Canonical cases supporting the public finding: ${(bug.publicCaseIds ?? bug.caseIds ?? []).join(', ')}`,
    `- Expected: ${bug.expected}`,
    `- Actual: ${bug.actual}`,
    `- GitHub Issue: ${bug.githubIssueUrl}`,
    `- Runtime evidence: ${(bug.publicEvidencePaths ?? bug.evidencePaths ?? []).join(', ')}`,
    `- Screenshot evidence: ${(bug.screenshotPaths ?? []).join(', ')}`,
    '',
  ]),
];
writeText('work/generated/bug-report.md', `${bugLines.join('\n')}\n`);
writeText('out/bug-report.md', bugLines.join('\n'));

const postmanFeatureLines = [
  '# HW06 Postman Features (Derived)',
  '',
  '> Generated from `work/registry/postman-features.json`; only features with real evidence are listed.',
  '',
  '| Feature | Verified usage | Evidence |',
  '|---|---|---|',
  ...features.map((feature) => `| ${markdownCell(feature.name)} | ${markdownCell(feature.usage)} | ${markdownCell((feature.evidencePaths ?? []).join(', '))} |`),
  '',
];
writeText('work/generated/postman-features.md', `${postmanFeatureLines.join('\n')}\n`);
writeText('out/postman-features.md', postmanFeatureLines.join('\n'));

function ciReportSummary(run) {
  const report = readJson(run.newmanReportPath);
  return {
    executionCount: report.run?.executions?.length ?? 0,
    assertionsTotal: report.run?.stats?.assertions?.total ?? 0,
    assertionsFailed: report.run?.stats?.assertions?.failed ?? run.failedAssertions,
  };
}

const allPassCiRun = ciRuns.find((run) => run.purpose === 'all-pass');
const intentionalFailureCiRun = ciRuns.find((run) => run.purpose === 'intentional-single-failure');
const canonicalFullSuiteCiRun = ciRuns.find((run) => run.purpose === 'canonical-full-suite');
const ciLines = [
  '# HW06 CI/CD Report (Derived)',
  '',
  '> Generated from `work/registry/ci-runs.json` and registered evidence. Screenshot attestation is reported independently from run verification.',
  '',
  '## Compliance status',
  '',
  '- CI infrastructure and complete canonical FR-04 integration: implemented.',
  '- Existing all-pass and intentional-single-failure smoke demonstration: complete as CI behavior evidence.',
  '- Strict assignment requirement that one pipeline run show "all API test cases passing": **PARTIAL / documented limitation due to confirmed SUT defects**.',
  '- The smoke all-pass result must not be interpreted as all 44 canonical FR-04 cases passing.',
  '',
];
if (canonicalFullSuiteCiRun) {
  const screenshot = evidence.find((item) => item.id === canonicalFullSuiteCiRun.screenshotEvidenceId);
  ciLines.push(
    '## Complete canonical FR-04 suite integration',
    '',
    '- Workflow: `.github/workflows/hw06-fr04-canonical-full-suite.yml` (`HW06 FR-04 Canonical Full Suite`).',
    '- The job installs locked dependencies, starts and reseeds the EShop backend for each independent execution group, and runs the current canonical collections/environment/data with Newman.',
    '- Newman JSON, HTML, stdout, copied inputs, canonical summary, exit codes, and backend logs are uploaded as `hw06-fr04-canonical-full-suite` before the final step exposes the genuine suite result.',
    `- Commit: ${canonicalFullSuiteCiRun.commitSha}`,
    `- GitHub Actions run: ${canonicalFullSuiteCiRun.url}`,
    `- Result: ${canonicalFullSuiteCiRun.conclusion}`,
    `- Canonical logical cases: ${canonicalFullSuiteCiRun.counts.executed}/${canonicalFullSuiteCiRun.counts.executable} executed; ${canonicalFullSuiteCiRun.counts.passed} passed; ${canonicalFullSuiteCiRun.counts.failed} failed.`,
    `- Failure classification: ${canonicalFullSuiteCiRun.counts.knownBugFailures} known-bug failures; ${canonicalFullSuiteCiRun.counts.otherFailures} other/specification-gap failure.`,
    `- Student-header runtime proof: ${canonicalFullSuiteCiRun.runtimeHeaderCoverage.studentHeaderRequests}/${canonicalFullSuiteCiRun.runtimeHeaderCoverage.requests} requests.`,
    `- Main collection SHA-256: ${canonicalFullSuiteCiRun.identities.mainCollectionSha256}`,
    `- Main data SHA-256: ${canonicalFullSuiteCiRun.identities.mainDataSha256}`,
    `- Canonical summary: ${canonicalFullSuiteCiRun.canonicalSummaryPath}`,
    `- Screenshot: ${canonicalFullSuiteCiRun.screenshotEvidenceId} (${screenshot?.path ?? 'missing'}; human attestation ${screenshot?.humanAttestation === true ? 'complete' : 'pending'})`,
    '',
    'The complete canonical FR-04 suite is retained as the authoritative API test suite and is executed in CI without weakening its test oracles. Because the suite currently exposes confirmed SUT defects, its real full-suite CI execution is expected to fail. Changing the expected results, suppressing the confirmed bug cases, or modifying the SUT solely to obtain a green pipeline would invalidate the testing evidence. Therefore, the separate stable-case runs are retained only to demonstrate an all-pass CI state and an intentional single-failure state, while the canonical full-suite CI run demonstrates that the complete FR-04 suite is genuinely integrated into the pipeline.',
    '',
  );
}
ciLines.push(
  '## CI behavior demonstration',
  '',
  '- Workflow: `.github/workflows/hw06-fr04-ci.yml` (`HW06 FR-04 Newman CI Sample`).',
  '- This workflow uses only the explicitly identified stable canonical case `FR04-AI-001` to demonstrate CI mechanics.',
  '- It injects `X-Student-Id: 23127179`, runs Newman, and uploads JSON/HTML/backend evidence as `hw06-fr04-ci-newman`.',
  '',
);
for (const [heading, run] of [['All-pass sample', allPassCiRun], ['Intentional single-failure sample', intentionalFailureCiRun]]) {
  if (!run) continue;
  const summary = ciReportSummary(run);
  const screenshot = evidence.find((item) => item.id === run.screenshotEvidenceId);
  ciLines.push(
    `## ${heading}`,
    '',
    `- Commit: ${run.commitSha}`,
    `- GitHub Actions run: ${run.url}`,
    `- Result: ${run.conclusion}`,
    `- Newman request executions: ${summary.executionCount}`,
    `- Assertions: ${summary.assertionsTotal} total, ${summary.assertionsFailed} failed`,
    `- Failed logical test cases: ${run.failedTests}`,
    `- Newman JSON: ${run.newmanReportPath}`,
    `- Screenshot: ${run.screenshotEvidenceId} (${screenshot?.path ?? 'missing'}; human attestation ${screenshot?.humanAttestation === true ? 'complete' : 'pending'})`,
    '',
  );
}
ciLines.push(
  '## Demonstration integrity note',
  '',
  'The intentional sample adds one transparent assertion named `FR04-AI-001 [CI-DEMO] intentional single failure`; it is not classified as an SUT bug. These two smoke runs demonstrate green/red CI behavior only and do not replace the complete canonical suite or prove that all 44 FR-04 cases pass.',
  '',
);
writeText('work/generated/ci-cd-report.md', `${ciLines.join('\n')}\n`);
writeText('out/ci-cd-report.md', ciLines.join('\n'));

function copyArtifact(source, target) {
  if (!fileExists(source)) throw new Error(`Cannot promote missing FR-04 artifact: ${source}`);
  const targetAbsolute = absoluteFromRepo(target);
  fs.mkdirSync(path.dirname(targetAbsolute), { recursive: true });
  fs.copyFileSync(absoluteFromRepo(source), targetAbsolute);
}

const officialRunIds = project.postman?.officialFr04RunIds ?? [];
const officialRuns = officialRunIds.map((id) => {
  const run = runs.find((candidate) => candidate.id === id);
  if (!run) throw new Error(`Unknown official FR-04 run: ${id}`);
  return run;
});
if (officialRuns.length > 0) {
  const primaryRun = officialRuns.find((run) => run.id === project.postman.officialFr04PrimaryRunId);
  if (!primaryRun) throw new Error('Official FR-04 primary run is not in officialFr04RunIds');
  const promotionPairs = [
    [project.postman.collectionPath, 'out/fr04/postman/FR04-profile.postman_collection.json'],
    [project.postman.supportingCollectionPaths[0], 'out/fr04/postman/FR04-profile-stateful.postman_collection.json'],
    [project.postman.environmentPath, 'out/fr04/postman/FR04-profile.postman_environment.json'],
    [project.postman.dataFiles[0], 'out/fr04/postman/FR04-cases.postman_data.json'],
    ['work/postman/fr04/FR04-target-closure.postman_data.json', 'out/fr04/postman/FR04-target-closure.postman_data.json'],
    ['work/postman/fr04/FR04-target-ai027.postman_data.json', 'out/fr04/postman/FR04-target-ai027.postman_data.json'],
    ['.github/workflows/hw06-fr04-ci.yml', 'out/fr04/ci/hw06-fr04-ci.yml'],
    ['.github/workflows/hw06-fr04-canonical-full-suite.yml', 'out/fr04/ci/hw06-fr04-canonical-full-suite.yml'],
    [primaryRun.rawJsonPath, 'out/fr04/newman/FR04-canonical-input.json'],
    [primaryRun.htmlReportPath, 'out/fr04/newman/FR04-canonical-input.html'],
    [primaryRun.consoleLogPath, 'out/fr04/newman/FR04-canonical-input.stdout.log'],
    [primaryRun.metadataPath, 'out/fr04/newman/FR04-canonical-input.metadata.json'],
  ];
  for (const item of evidence.filter((candidate) => candidate.id.startsWith('EVID-FR04-') && candidate.humanAttestation === true)) {
    promotionPairs.push([item.path, `out/fr04/evidence/${item.id}.png`]);
  }
  const finalizedCiDemoEvidenceIds = new Set([
    'EVID-CI-FR04-ALL-PASS',
    'EVID-CI-FR04-INTENTIONAL-FAILURE',
  ]);
  for (const item of evidence.filter((candidate) => finalizedCiDemoEvidenceIds.has(candidate.id) && candidate.humanAttestation === true)) {
    promotionPairs.push([item.path, `out/fr04/evidence/${item.id}.png`]);
  }
  const statefulRun = officialRuns.find((run) => run.id.includes('final-stateful'));
  if (statefulRun) promotionPairs.push(
    [statefulRun.rawJsonPath, 'out/fr04/newman/FR04-final-stateful.json'],
    [statefulRun.htmlReportPath, 'out/fr04/newman/FR04-final-stateful.html'],
    [statefulRun.consoleLogPath, 'out/fr04/newman/FR04-final-stateful.stdout.log'],
    [statefulRun.metadataPath, 'out/fr04/newman/FR04-final-stateful.metadata.json'],
  );
  const closureRun = officialRuns.find((run) => run.dataPath?.endsWith('FR04-target-closure.postman_data.json'));
  if (closureRun) promotionPairs.push(
    [closureRun.rawJsonPath, 'out/fr04/newman/FR04-final-closure.json'],
    [closureRun.htmlReportPath, 'out/fr04/newman/FR04-final-closure.html'],
    [closureRun.consoleLogPath, 'out/fr04/newman/FR04-final-closure.stdout.log'],
    [closureRun.metadataPath, 'out/fr04/newman/FR04-final-closure.metadata.json'],
  );
  const ai027Run = officialRuns.find((run) => run.dataPath?.endsWith('FR04-target-ai027.postman_data.json'));
  if (ai027Run) promotionPairs.push(
    [ai027Run.rawJsonPath, 'out/fr04/newman/FR04-ai027-corrected.json'],
    [ai027Run.htmlReportPath, 'out/fr04/newman/FR04-ai027-corrected.html'],
    [ai027Run.consoleLogPath, 'out/fr04/newman/FR04-ai027-corrected.stdout.log'],
    [ai027Run.metadataPath, 'out/fr04/newman/FR04-ai027-corrected.metadata.json'],
  );
  for (const [source, target] of promotionPairs) copyArtifact(source, target);
  const manifestLines = [
    '# FR-04 Finalized Artifacts',
    '',
    '> Promoted from canonical registries and official raw runs by `npm run hw06:derive`.',
    '',
    `- Primary run: ${primaryRun.id}`,
    `- Collection SHA-256: ${primaryRun.collectionSha256}`,
    `- Environment SHA-256: ${primaryRun.environmentSha256}`,
    `- Data SHA-256: ${primaryRun.dataSha256}`,
    `- Primary Newman HTML: out/fr04/newman/FR04-canonical-input.html`,
    `- Supporting official runs: ${officialRuns.filter((run) => run.id !== primaryRun.id).map((run) => run.id).join(', ')}`,
    '- Finalized CI demo screenshots: out/fr04/evidence/EVID-CI-FR04-ALL-PASS.png and out/fr04/evidence/EVID-CI-FR04-INTENTIONAL-FAILURE.png',
    '- CI workflow configurations: out/fr04/ci/hw06-fr04-ci.yml and out/fr04/ci/hw06-fr04-canonical-full-suite.yml',
    '- Canonical full-suite CI screenshot remains under work/evidence until explicit human attestation.',
    '',
    'The primary run preserves genuine bug-revealing failures. Latest canonical per-case results across the listed official runs are summarized in `work/generated/test-summary.md`.',
    '',
  ];
  writeText('out/fr04/README.md', manifestLines.join('\n'));
}

for (const bug of bugs.filter((item) => item.status !== 'candidate')) {
  const issueBody = [
    `# ${bug.id}: ${bug.title}`,
    '',
    `Test cases: ${(bug.publicCaseIds ?? bug.caseIds ?? []).join(', ')}`,
    '',
    '## Expected behavior',
    '',
    bug.expected,
    '',
    '## Actual behavior',
    '',
    bug.actual,
    '',
    '## Reproduction',
    '',
    bug.reproduction ?? 'NOT RECORDED',
    '',
    '## Local evidence paths',
    '',
    ...(bug.publicEvidencePaths ?? bug.evidencePaths ?? []).map((item) => `- ${item}`),
    '',
    '> Attach the required screenshot in GitHub before publishing. A local path is not a public attachment.',
    '',
  ];
  writeText(`work/generated/issues/${bug.id}.md`, `${issueBody.join('\n')}\n`);
}

const evidenceTypes = new Set(evidence.map((item) => item.type));
function artifactPath(artifact) {
  if (artifact.path) return artifact.path;
  if (artifact.pathFrom === 'project.postman.collectionPath') return project.postman?.collectionPath;
  return null;
}
const submissionLines = [
  '# HW06 Submission Status (Derived)',
  '',
  '| Requirement | Source | Status |',
  '|---|---|---|',
  ...(submission.requiredArtifacts ?? []).map((artifact) => {
    const candidatePath = artifactPath(artifact);
    const present = candidatePath ? fileExists(candidatePath) : evidenceTypes.has(artifact.evidenceType);
    return `| ${artifact.id} | ${candidatePath ?? `evidence:${artifact.evidenceType}`} | ${present ? 'PRESENT' : 'MISSING'} |`;
  }),
  '',
  '## Required evidence types',
  '',
  ...(submission.requiredEvidenceTypes ?? []).map((type) => `- [${evidenceTypes.has(type) ? 'x' : ' '}] ${type}`),
  '',
  `CI all-pass records: ${ciRuns.filter((run) => run.purpose === 'all-pass').length}`,
  `CI intentional-single-failure records: ${ciRuns.filter((run) => run.purpose === 'intentional-single-failure').length}`,
  `Postman features recorded: ${features.length}`,
  '',
];
writeText('work/generated/submission-status.md', `${submissionLines.join('\n')}\n`);

process.stdout.write('Generated factual summaries under work/generated/.\n');
