import {
  fileExists,
  markdownCell,
  readJson,
  writeJson,
  writeText,
} from './common.mjs';

const project = readJson('work/registry/project.json');
const cases = readJson('work/registry/test-cases.json').cases;
const reviews = readJson('work/registry/human-reviews.json').reviews;
const runs = readJson('work/registry/runs.json').runs;
const bugs = readJson('work/registry/bugs.json').bugs;
const ciRuns = readJson('work/registry/ci-runs.json').runs;
const evidence = readJson('work/registry/evidence.json').items;
const features = readJson('work/registry/postman-features.json').features;
const submission = readJson('work/registry/submission.json');

const reviewByCase = new Map(reviews.map((review) => [review.caseId, review]));
const resultsByCase = new Map();
for (const run of runs) {
  for (const result of run.caseResults ?? []) {
    if (!resultsByCase.has(result.caseId)) resultsByCase.set(result.caseId, []);
    resultsByCase.get(result.caseId).push(`${run.id}:${result.result}`);
  }
}
const bugsByCase = new Map();
for (const bug of bugs) {
  for (const caseId of bug.caseIds ?? []) {
    if (!bugsByCase.has(caseId)) bugsByCase.set(caseId, []);
    bugsByCase.get(caseId).push(bug.id);
  }
}

const apiRows = project.selectedApis.map((api) => {
  const apiCases = cases.filter((testCase) => testCase.apiId === api.id);
  return {
    id: api.id,
    pool: api.pool,
    feature: api.featureId,
    endpoint: `${api.method} ${api.path}`,
    aiGenerated: apiCases.filter((testCase) => testCase.origin === 'AI').length,
    humanAdded: apiCases.filter((testCase) => testCase.origin === 'HUMAN').length,
    audited: apiCases.filter((testCase) => testCase.origin === 'AI' && reviewByCase.has(testCase.id)).length,
    executed: apiCases.filter((testCase) => resultsByCase.has(testCase.id)).length,
    passed: apiCases.filter((testCase) => (resultsByCase.get(testCase.id) ?? []).some((result) => result.endsWith(':PASS'))).length,
    failed: apiCases.filter((testCase) => (resultsByCase.get(testCase.id) ?? []).some((result) => result.endsWith(':FAIL'))).length,
  };
});

const totals = apiRows.reduce((result, row) => {
  for (const field of ['aiGenerated', 'humanAdded', 'audited', 'executed', 'passed', 'failed']) result[field] += row[field];
  return result;
}, { aiGenerated: 0, humanAdded: 0, audited: 0, executed: 0, passed: 0, failed: 0 });

writeJson('work/generated/test-summary.json', {
  generatedAtUtc: new Date().toISOString(),
  selectedApiCount: project.selectedApis.length,
  apis: apiRows,
  totals,
  bugCount: bugs.filter((bug) => bug.status !== 'candidate').length,
});

const summaryLines = [
  '# HW06 Test Summary (Derived)',
  '',
  '> Generated from `work/registry/`; do not edit this file manually.',
  '',
  '| API | Pool | Feature | Endpoint | AI generated | Human added | Audited | Executed | Passed | Failed |',
  '|---|---|---|---|---:|---:|---:|---:|---:|---:|',
  ...apiRows.map((row) => `| ${row.id} | ${row.pool} | ${row.feature} | ${row.endpoint} | ${row.aiGenerated} | ${row.humanAdded} | ${row.audited} | ${row.executed} | ${row.passed} | ${row.failed} |`),
  '',
  `Selected APIs: ${project.selectedApis.length}`,
  `AI-generated cases: ${totals.aiGenerated}`,
  `Human-added cases: ${totals.humanAdded}`,
  `Executed cases: ${totals.executed}`,
  `Passed cases: ${totals.passed}`,
  `Failed cases: ${totals.failed}`,
  `Human-confirmed/published bugs: ${bugs.filter((bug) => bug.status !== 'candidate').length}`,
  '',
];
writeText('work/generated/test-summary.md', `${summaryLines.join('\n')}\n`);

const traceabilityLines = [
  '# HW06 Traceability Matrix (Derived)',
  '',
  '> Generated from canonical registries. Empty cells mean missing traceability, not absence of a requirement.',
  '',
  '| Case | API | Origin | Requirement refs | AI source context | Human verdict | Run results | Bugs |',
  '|---|---|---|---|---|---|---|---|',
  ...cases.map((testCase) => {
    const review = reviewByCase.get(testCase.id);
    return `| ${markdownCell(testCase.id)} | ${markdownCell(testCase.apiId)} | ${markdownCell(testCase.origin)} | ${markdownCell((testCase.requirementRefs ?? []).join(', '))} | ${markdownCell(testCase.generationContext ?? '')} | ${markdownCell(review?.verdict ?? (testCase.origin === 'HUMAN' ? 'HUMAN-AUTHORED' : 'MISSING'))} | ${markdownCell((resultsByCase.get(testCase.id) ?? []).join(', '))} | ${markdownCell((bugsByCase.get(testCase.id) ?? []).join(', '))} |`;
  }),
  '',
];
writeText('work/generated/traceability.md', `${traceabilityLines.join('\n')}\n`);

const bugLines = [
  '# HW06 Bug Report (Derived)',
  '',
  '> Candidate records are not claims of genuine bugs. Only human-confirmed or published records are reportable.',
  '',
  '| Bug | Status | Cases | Expected | Actual | GitHub Issue |',
  '|---|---|---|---|---|---|',
  ...bugs.map((bug) => `| ${markdownCell(bug.id)} | ${markdownCell(bug.status)} | ${markdownCell((bug.caseIds ?? []).join(', '))} | ${markdownCell(bug.expected ?? '')} | ${markdownCell(bug.actual ?? '')} | ${markdownCell(bug.githubIssueUrl ?? '')} |`),
  '',
];
writeText('work/generated/bug-report.md', `${bugLines.join('\n')}\n`);

for (const bug of bugs.filter((item) => item.status !== 'candidate')) {
  const issueBody = [
    `# ${bug.id}: ${bug.title}`,
    '',
    `Test cases: ${(bug.caseIds ?? []).join(', ')}`,
    `Confirmed by: ${bug.confirmedBy}`,
    `Confirmed at: ${bug.confirmedAt ?? 'NOT RECORDED'}`,
    '',
    '## Expected behavior',
    '',
    bug.expected,
    '',
    '## Actual behavior',
    '',
    bug.actual,
    '',
    '## Reproduction',
    '',
    bug.reproduction ?? 'NOT RECORDED',
    '',
    '## Local evidence paths',
    '',
    ...(bug.evidencePaths ?? []).map((item) => `- ${item}`),
    '',
    '> Attach the required screenshot in GitHub before publishing. A local path is not a public attachment.',
    '',
  ];
  writeText(`work/generated/issues/${bug.id}.md`, `${issueBody.join('\n')}\n`);
}

const evidenceTypes = new Set(evidence.map((item) => item.type));
function artifactPath(artifact) {
  if (artifact.path) return artifact.path;
  if (artifact.pathFrom === 'project.postman.collectionPath') return project.postman?.collectionPath;
  return null;
}
const submissionLines = [
  '# HW06 Submission Status (Derived)',
  '',
  '| Requirement | Source | Status |',
  '|---|---|---|',
  ...(submission.requiredArtifacts ?? []).map((artifact) => {
    const candidatePath = artifactPath(artifact);
    const present = candidatePath ? fileExists(candidatePath) : evidenceTypes.has(artifact.evidenceType);
    return `| ${artifact.id} | ${candidatePath ?? `evidence:${artifact.evidenceType}`} | ${present ? 'PRESENT' : 'MISSING'} |`;
  }),
  '',
  '## Required evidence types',
  '',
  ...(submission.requiredEvidenceTypes ?? []).map((type) => `- [${evidenceTypes.has(type) ? 'x' : ' '}] ${type}`),
  '',
  `CI all-pass records: ${ciRuns.filter((run) => run.purpose === 'all-pass').length}`,
  `CI intentional-single-failure records: ${ciRuns.filter((run) => run.purpose === 'intentional-single-failure').length}`,
  `Postman features recorded: ${features.length}`,
  '',
];
writeText('work/generated/submission-status.md', `${submissionLines.join('\n')}\n`);

process.stdout.write('Generated factual summaries under work/generated/.\n');
